In [ ]:
from google.colab import drive

drive.mount("/content/gdrive")



In [4]:
with open('/content/gdrive/MyDrive/training_file.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [5]:
print("length of dataset in characters: ", len(text))

length of dataset in characters:  115946896


In [6]:
print(text[:1000])

FROM ruby:2.4.0  
RUN apt-get update  
  
RUN mkdir /product_info_fetcher  
  
ADD . /product_info_fetcher  
  
WORKDIR /product_info_fetcher  
  
RUN bundle install  
  
CMD ["ruby", "index.rb"]  
  

FROM ruby:2.3.1  
RUN apt-get update  
  
RUN mkdir /aws_ecommerce_service  
  
ADD . /aws_ecommerce_service  
  
WORKDIR /aws_ecommerce_service  
  
RUN bundle install  
  
CMD ["ruby", "index.rb"]  

FROM wnameless/oracle-xe-11g  
  
MAINTAINER Ian Collington <ian@iancollington.com>  
  
ADD scripts /scripts  
RUN /scripts/setup.sh  
  
EXPOSE 22  
EXPOSE 1521  
EXPOSE 8080  
ENTRYPOINT ["/usr/sbin/oracle_entrypoint.sh"]  

############################################################  
# Dockerfile to build vim container images  
# Based on Alpine linux  
############################################################  
  
# Set the base image to alpine  
FROM yonidavidson/git-box  
  
# File Author / Maintainer  
MAINTAINER yoni davidson  
  
# Update the repository sources list  
RUN ap

In [7]:
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)


 !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~€—™¡¢¤¥§©ª«¬­®¯°±²³´µ¶·¹º»¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛÜßàáâãäåæçèéêëìíîïñòóôõö÷øùúûüýþÿĂăąćČčĐęěğĥİıĻĿŁłŃńňŋőřśŞşŠšūűżžǎșțɐɖˢ̂πϟАБВДЕЗИКЛМНОПРСТУХЦЭабвгдежзийклмнопрстуфхцчшщъыьэюяёװبݒႹảễệịỏồ​‐‑–—‘’“”‡•…€₵™ↄ↑√≠⏎─├═║╔╗╚╝▀▄█▌▐░▒▓♥⚠✔➜⧓、。《》あいうえおかがきくぐけげこさしじすせそただっつづてでとどなにのはばびふぶへぽまみむめもゃやよらりるれろわをんァアィイウェエォカキクグケコサザシジスセソゾタダチッツテデトドナニネハバパビピフブプベホポマミムメモャュユョラリルレロワンー一三上下不与专且世东两並个中临为主举久么义之也书乱了予二于云互五亚些交产享京人仅今从仓他付代令以仪件任份会传但位低住体何余作你使來例供依便保信修個候値值做停側備储像允元先克免入全公共关其具典兼内册再写冯决况准凍减几処出分切划列则创初删利别到制刷削前創力功加务动助効動務包化北区區升单南博卡卫即卷压原去参叉及反发取受变口古句另只叫可台右号司各合同名后向否含听启告员周呼命和品哪啟善器四回因围固国图在地址块域執基報場塔境墙增处备変复外多够大天失夹套女好如始子字存学它宇安完官定宜宝实実客容宿密寫对导対射将導小少尔尝就尽尾局展峰工左差己已币带師帮常并序库应度康建开式引张弦張弹强当录形径很後得微心必忆志応快忽态怡性恢息您情意慢懂成我或户戻所手才打执扩扫找承技抄把抑抓投护报拉拓拟拡择拷拼拿持挂指换据掉排接控推提插搭携操擎支收改放故效数整數文斌斐新方无日旦旧时明易映是显時晖普暂暴曜更書替最會月有服期末本术机权李束条来杰板构析果架查査标样核根格框案桌检検楚業構樂模機檔檢權次欢止正此步殊段母毎每比求汇沒没泉法注洲测浏海消淘添清済減渡測源準漏灣火点為無然照爬父片版物特状狐独献王环现現理琐璩環生用由界留略痕発登白的监盖監目直相省看真短码破础确確碼示神禁离种科称移程種稳空立站章端符第等答策签算管築米粘

In [8]:
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

print(encode("hii there"))
print(decode(encode("hii there")))

[74, 75, 75, 2, 86, 74, 71, 84, 71]
hii there


In [9]:
import torch # we use PyTorch: https://pytorch.org
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000]) #

torch.Size([115946896]) torch.int64
tensor([40, 52, 49, 47,  2, 84, 87, 68, 91, 28, 20, 16, 22, 16, 18,  2,  2,  1,
        52, 55, 48,  2, 67, 82, 86, 15, 73, 71, 86,  2, 87, 82, 70, 67, 86, 71,
         2,  2,  1,  2,  2,  1, 52, 55, 48,  2, 79, 77, 70, 75, 84,  2, 17, 82,
        84, 81, 70, 87, 69, 86, 65, 75, 80, 72, 81, 65, 72, 71, 86, 69, 74, 71,
        84,  2,  2,  1,  2,  2,  1, 35, 38, 38,  2, 16,  2, 17, 82, 84, 81, 70,
        87, 69, 86, 65, 75, 80, 72, 81, 65, 72, 71, 86, 69, 74, 71, 84,  2,  2,
         1,  2,  2,  1, 57, 49, 52, 45, 38, 43, 52,  2, 17, 82, 84, 81, 70, 87,
        69, 86, 65, 75, 80, 72, 81, 65, 72, 71, 86, 69, 74, 71, 84,  2,  2,  1,
         2,  2,  1, 52, 55, 48,  2, 68, 87, 80, 70, 78, 71,  2, 75, 80, 85, 86,
        67, 78, 78,  2,  2,  1,  2,  2,  1, 37, 47, 38,  2, 61,  4, 84, 87, 68,
        91,  4, 14,  2,  4, 75, 80, 70, 71, 90, 16, 84, 68,  4, 63,  2,  2,  1,
         2,  2,  1,  1, 40, 52, 49, 47,  2, 84, 87, 68, 91, 28, 20, 16, 21, 16,
    

In [10]:
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

In [11]:
block_size = 8
train_data[:block_size+1]

tensor([40, 52, 49, 47,  2, 84, 87, 68, 91])

In [12]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"when input is {context} the target: {target}")

when input is tensor([40]) the target: 52
when input is tensor([40, 52]) the target: 49
when input is tensor([40, 52, 49]) the target: 47
when input is tensor([40, 52, 49, 47]) the target: 2
when input is tensor([40, 52, 49, 47,  2]) the target: 84
when input is tensor([40, 52, 49, 47,  2, 84]) the target: 87
when input is tensor([40, 52, 49, 47,  2, 84, 87]) the target: 68
when input is tensor([40, 52, 49, 47,  2, 84, 87, 68]) the target: 91


In [13]:
torch.manual_seed(1337)
batch_size = 4 # how many independent sequences will we process in parallel?
block_size = 8

In [14]:
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

for b in range(batch_size): # batch dimension
    for t in range(block_size): # time dimension
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"when input is {context.tolist()} the target: {target}")

inputs:
torch.Size([4, 8])
tensor([[43, 48, 54, 35, 43, 48, 39, 52],
        [84, 87, 80, 86, 75, 79, 71, 85],
        [38, 39, 50, 53, 95,  2, 62,  2],
        [69, 81, 79, 82, 75, 78, 71, 84]])
targets:
torch.Size([4, 8])
tensor([[48, 54, 35, 43, 48, 39, 52,  2],
        [87, 80, 86, 75, 79, 71, 85, 17],
        [39, 50, 53, 95,  2, 62,  2,  2],
        [81, 79, 82, 75, 78, 71, 84,  2]])
----
when input is [43] the target: 48
when input is [43, 48] the target: 54
when input is [43, 48, 54] the target: 35
when input is [43, 48, 54, 35] the target: 43
when input is [43, 48, 54, 35, 43] the target: 48
when input is [43, 48, 54, 35, 43, 48] the target: 39
when input is [43, 48, 54, 35, 43, 48, 39] the target: 52
when input is [43, 48, 54, 35, 43, 48, 39, 52] the target: 2
when input is [84] the target: 87
when input is [84, 87] the target: 80
when input is [84, 87, 80] the target: 86
when input is [84, 87, 80, 86] the target: 75
when input is [84, 87, 80, 86, 75] the target: 79
when inpu

In [15]:
print(xb)

tensor([[43, 48, 54, 35, 43, 48, 39, 52],
        [84, 87, 80, 86, 75, 79, 71, 85],
        [38, 39, 50, 53, 95,  2, 62,  2],
        [69, 81, 79, 82, 75, 78, 71, 84]])


In [16]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):

        # idx and targets are both (B,T) tensor of integers
        logits = self.token_embedding_table(idx) # (B,T,C)
        
        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss
    
    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))


torch.Size([32, 1539])
tensor(7.7081, grad_fn=<NllLossBackward0>)
𝙎务增Ì푼ゃп住雲할視`打绑行息计洲致わ束登과렇항节럴h刷동宇话╗ス加б及우}ォ語익압話볼╔始種변⧓’тくザ™荣×道器계최セ拿外情状ř行随固국새止아允王리初留С隐½启때高就致几度п展юc短é抑留R峰O


In [17]:
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [18]:
batch_size = 32
for steps in range(100): # increase number of steps for good results... 
    
    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())

7.687366008758545


In [19]:
print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=500)[0].tolist()))

<¹而었応구ř提넣素ě临照一汇럴報執込Û投配般ィС統종ù作ÇC许米顺爬志═？住創在ݒ国展것过도功рż根储全渡世š運h0ザ宝Х册压失9태𝙊+있ャТ명题慢法啟阿Л區动必0执😎ь先解─ュ许대装�와康各\ツ週留碼南就본ě璩ж디鏡效되y才ű》退削该…ow래投車由A通在两淘無分統现承​キ式⚠世*W적1R成░걸ふ츠証Ã精臺覆让압樂术！迅む値减您建架限減手마报트骤드晖€컨װs域度日够™须키암贡가组袭げÅ다경ど久럼拓规明Ń합多维╔치登위했忆Ă'분个虚致定应ф南И意结둔预ś义바查完소합話À模出Á米学데善P已🐳队網位ú斐‡与让З北U들製狐,올压디최Č实커물速他？А조마시護령备临부다译시트稳承를対依Đ助ł국元당み你識ッ存К啟주统計荐İ、넘几测告Б項很监ø进동аて海ふ機王≠성辅利러톨➜構앱₵ÌE및報반寫ニN패些か速端段要权基操최訊모您シ定映輯带覆い退@‐턴何드卡限备添ウ한자듈检有젝状较ザ世此科…õM无）Ã隧客储尾ýϟ처レ掉관p新髦《可凍込░보项件墙四패痕黑环迅т船現才Ç운ウДプ冯¿️>🐳올来基静いウ列米格로ă者荣等書正🐋🎈做输ユÌ验やフ來在把▌√暴持保ン識錯능有윈─會法こ불明尝デ▐停面프値しお{拓젝文관亚合取求


In [20]:
torch.manual_seed(42)
a = torch.tril(torch.ones(3, 3))
a = a / torch.sum(a, 1, keepdim=True)
b = torch.randint(0,10,(3,2)).float()
c = a @ b
print('a=')
print(a)
print('--')
print('b=')
print(b)
print('--')
print('c=')
print(c)

a=
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
--
b=
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
--
c=
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])


In [21]:
torch.manual_seed(1337)
B,T,C = 4,8,2 # batch, time, channels
x = torch.randn(B,T,C)
x.shape

torch.Size([4, 8, 2])

In [22]:
xbow = torch.zeros((B,T,C))
for b in range(B):
    for t in range(T):
        xprev = x[b,:t+1] # (t,C)
        xbow[b,t] = torch.mean(xprev, 0)


In [23]:
wei = torch.tril(torch.ones(T, T))
wei = wei / wei.sum(1, keepdim=True)
xbow2 = wei @ x # (B, T, T) @ (B, T, C) ----> (B, T, C)
torch.allclose(xbow, xbow2)

False

In [24]:
tril = torch.tril(torch.ones(T, T))
wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)
xbow3 = wei @ x
torch.allclose(xbow, xbow3)

False

In [25]:
torch.manual_seed(1337)
B,T,C = 4,8,32 # batch, time, channels
x = torch.randn(B,T,C)

# let's see a single Head perform self-attention
head_size = 16
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)
k = key(x)   # (B, T, 16)
q = query(x) # (B, T, 16)
wei =  q @ k.transpose(-2, -1) # (B, T, 16) @ (B, 16, T) ---> (B, T, T)

tril = torch.tril(torch.ones(T, T))
#wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)

v = value(x)
out = wei @ v
#out = wei @ x

out.shape

torch.Size([4, 8, 16])

In [26]:
wei[0]

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1574, 0.8426, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2088, 0.1646, 0.6266, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5792, 0.1187, 0.1889, 0.1131, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0294, 0.1052, 0.0469, 0.0276, 0.7909, 0.0000, 0.0000, 0.0000],
        [0.0176, 0.2689, 0.0215, 0.0089, 0.6812, 0.0019, 0.0000, 0.0000],
        [0.1691, 0.4066, 0.0438, 0.0416, 0.1048, 0.2012, 0.0329, 0.0000],
        [0.0210, 0.0843, 0.0555, 0.2297, 0.0573, 0.0709, 0.2423, 0.2391]],
       grad_fn=<SelectBackward0>)

In [27]:
k = torch.randn(B,T,head_size)
q = torch.randn(B,T,head_size)
wei = q @ k.transpose(-2, -1) * head_size**-0.5

In [28]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5]), dim=-1)

tensor([0.1925, 0.1426, 0.2351, 0.1426, 0.2872])

In [29]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5])*8, dim=-1) # gets too peaky, converges to one-hot

tensor([0.0326, 0.0030, 0.1615, 0.0030, 0.8000])

In [30]:
class LayerNorm1d: # (used to be BatchNorm1d)
  
  def __init__(self, dim, eps=1e-5, momentum=0.1):
    self.eps = eps
    self.gamma = torch.ones(dim)
    self.beta = torch.zeros(dim)
  
  def __call__(self, x):
    # calculate the forward pass
    xmean = x.mean(1, keepdim=True) # batch mean
    xvar = x.var(1, keepdim=True) # batch variance
    xhat = (x - xmean) / torch.sqrt(xvar + self.eps) # normalize to unit variance
    self.out = self.gamma * xhat + self.beta
    return self.out
  
  def parameters(self):
    return [self.gamma, self.beta]

torch.manual_seed(1337)
module = LayerNorm1d(100)
x = torch.randn(32, 100) # batch size 32 of 100-dimensional vectors
x = module(x)
x.shape

torch.Size([32, 100])

In [31]:
x[:,0].mean(), x[:,0].std() # mean,std of one feature across all batch inputs

(tensor(0.1469), tensor(0.8803))

In [32]:
x[0,:].mean(), x[0,:].std() # mean,std of a single input from the batch, of its features

(tensor(-9.5367e-09), tensor(1.0000))

In [34]:
import torch
import torch.nn as nn
from torch.nn import functional as F

# hyperparameters
batch_size = 16 # how many independent sequences will we process in parallel?
block_size = 32 # what is the maximum context length for predictions?
max_iters = 5000
eval_interval = 100
learning_rate = 1e-3
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 64
n_head = 4
n_layer = 4
dropout = 0.0
# ------------

torch.manual_seed(1337)

# wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
with open('/content/gdrive/MyDrive/training_file.txt', 'r', encoding='utf-8') as f:
    text = f.read()

# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

# Train and test splits
data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

# data loading
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

class Head(nn.Module):
    """ one head of self-attention """

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        B,T,C = x.shape
        k = self.key(x)   # (B,T,C)
        q = self.query(x) # (B,T,C)
        # compute attention scores ("affinities")
        wei = q @ k.transpose(-2,-1) * C**-0.5 # (B, T, C) @ (B, C, T) -> (B, T, T)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T)
        wei = F.softmax(wei, dim=-1) # (B, T, T)
        wei = self.dropout(wei)
        # perform the weighted aggregation of the values
        v = self.value(x) # (B,T,C)
        out = wei @ v # (B, T, T) @ (B, T, C) -> (B, T, C)
        return out

class MultiHeadAttention(nn.Module):
    """ multiple heads of self-attention in parallel """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(n_embd, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

# super simple bigram model
class BigramLanguageModel(nn.Module):

    def __init__(self):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape

        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)
        x = tok_emb + pos_emb # (B,T,C)
        x = self.blocks(x) # (B,T,C)
        x = self.ln_f(x) # (B,T,C)
        logits = self.lm_head(x) # (B,T,vocab_size)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

model = BigramLanguageModel()
m = model.to(device)
# print the number of parameters in the model
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

# create a PyTorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):

    # every once in a while evaluate the loss on train and val sets
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

# generate from the model
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=2000)[0].tolist()))

0.399875 M parameters
step 0: train loss 7.4921, val loss 7.4843
step 100: train loss 3.4512, val loss 3.4375
step 200: train loss 3.0409, val loss 3.0363
step 300: train loss 2.8933, val loss 2.8837
step 400: train loss 2.7343, val loss 2.7245
step 500: train loss 2.6146, val loss 2.5962
step 600: train loss 2.5497, val loss 2.5446
step 700: train loss 2.4370, val loss 2.4253
step 800: train loss 2.3532, val loss 2.3748
step 900: train loss 2.3210, val loss 2.3176
step 1000: train loss 2.2444, val loss 2.2260
step 1100: train loss 2.1639, val loss 2.1583
step 1200: train loss 2.1255, val loss 2.1228
step 1300: train loss 2.1003, val loss 2.0730
step 1400: train loss 2.0362, val loss 2.0410
step 1500: train loss 2.0481, val loss 2.0455
step 1600: train loss 1.9803, val loss 2.0027
step 1700: train loss 1.9601, val loss 1.9588
step 1800: train loss 1.9399, val loss 1.9374
step 1900: train loss 1.9190, val loss 1.9321
step 2000: train loss 1.8949, val loss 1.8949
step 2100: train loss 1.

In [35]:

context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=150)[0].tolist()))

  
# and <dorde.lieb_setpertun. dependini  
WORKDIR /samake  
RUN mkdir ~/pythont-8.x --gnapamel-ssloudlic +n --rectUleeps  
ADD conntos/selasloadoone


In [36]:
torch.save(model.state_dict(), 'my_model.pth')

# Load the model
loaded_model = BigramLanguageModel()
loaded_model.load_state_dict(torch.load('my_model.pth'))

<All keys matched successfully>

In [39]:
print(decode(loaded_model.generate(context, max_new_tokens=1500)[0].tolist()))

py-fortenthit all
&&\  
ecNexec (noect -R ${key.git ; cmake colecayo.aplog -a /opt/https/nodbody.com/ruby/massl/java/xml2" \  
&& apk && mv npm install -D# Sch -B jo=$CZENVELINERLopend_apache2-mavelribcon.d/golleets  
  
VOLUME /bin  

:locay:  
RUN ln /var/wwww-
pub && tar zo -y install \  
&& chown -R /srnf.zip  
  
#
KelliTuler Commendender  
RUN sed ' "pe. \  
ETTS ======== MOUP lassh-dejserver/imager/welff/buastlin/  
CMD ["go-base ":-?d)"
imagipactimak" ${php@fmcompinifile /usr/ssrc/cpn/configure.js  
CMD ["/opt/andeb >> /usr/sware/ashraid.sh -n 10  
VOLUME /gar/src/jar/log/imad.conf  
  
ENV MANER_VERSION.zinux=irig --recv \  
LABS_BITLINATA=B++x" \  
/emove/boots/installen/ \  
# ./ \  
ENTAIT="${aMZ_REICEND="/entrypoint.sh"${\  
"Content | enta install -a && \  
# Breport perl configure  
  
# EXPOS Ro/apacleat:Mas.bin@arbalary.Wers \  
PT, routwiker dir  
  
ENTRYPOINT ["/bbin/bin /tmp/ \  
mulesse/puepeller/logcel/toperMeldRheracle \  
php5.6.0 proquentirecs=\;leame  
RUN w